### ISSUE TITLE
nutcracker: cannot use info command

### ISSUE THREAD

**Issue by ORESoftware** [t-k/nutcracker_node#3]
I have a 2 line node.js script that's throwing this error totally unexpectedly, another guy in my office is having the same problem with a totally different codebase, so I know it's not just me

here's the error output (in red):
nutcracker: cannot use info command

this is the program (2 lines)

var nutcracker = require('nutcracker');
var client = nutcracker.createClient('6379', '127.0.0.1');

how can this be???

**Comment by t-k** [comment]
INFO Command is not supported on twemproxy.
https://github.com/twitter/twemproxy/blob/master/notes/redis.md#server
